#!/usr/bin/env python

"""Convert notebooks to and from the ipyaml format.  The new notebooks will be
written to the same directory with appropriate file extensions.
"""

import argparse
import os
import sys

import nbformat
from ipyaml.yamlnbformat import read, write

def convert_nb(fn, delete_old):
    if fn.endswith('.ipynb'):
        nb = nbformat.read(fn, nbformat.NO_CONVERT)
        write(nb, open(fn.replace('.ipynb', '.ipyaml'), 'w'))
    elif fn.endswith('.ipyaml'):
        nb = read(open(fn, 'r'), nbformat.NO_CONVERT)
        nbformat.write(nb, fn.replace('.ipyaml', '.ipynb'))
    else:
        sys.stderr.write('Did not recognize file type: %s\n' % fn)
        return
    if args.delete:
        os.unlink(fn)

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('notebook', nargs='+', help='Notebook to convert')
    parser.add_argument('-d', '--delete', action='store_true', default=False,
                        help='Delete existing notebook after conversion')
    args = parser.parse_args()

    for fn in args.notebook:
        convert_nb(fn, args.delete)
